apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: okui8of0r-go
  janus-idp.io/tekton: okui8of0r-go
  backstage.io/kubernetes-id: okui8of0r-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: okui8of0r-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
